CREATE TABLE IF NOT EXISTS
aricle(
    id INTEGER PRIMARY KEY GENERATED ALWAYS  AS IDENTITY,
    headline VARCHAR(500) NOT NULL,
    subhead VARCHAR(500) NOT NULL,
    content VARCHAR(500) NOT NULL,
    cover VARCHAR(500) NOT NULL
);



CREATE TABLE IF NOT EXISTS
category(
    id INTEGER PRIMARY KEY GENERATED ALWAYS  AS IDENTITY,
    category VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS
authors(
    id INTEGER PRIMARY KEY GENERATED ALWAYS  AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    img VARCHAR(500) NOT NULL
);

